/* This file is gerated by generate_c_code.py script, do not modify. */
#define IOCOM_IOBOARD
#include "iocom.h"
#include "pinsx.h"
#include "config/include/esphw/signals.h"
#include "config/include/esphw/signals-info-mblk.h"
#include "config/include/esphw/pins-io.h"
#include "config/include/esphw/network_defaults.h"
#include "config/include/esphw/candy-signals.h"
#include "config/include/esphw/gina-signals.h"
#include "config/include/esphw/signals.c"
#include "config/include/esphw/signals-info-mblk.c"
#include "config/include/esphw/pins-io.c"
#include "config/include/esphw/network_defaults.c"
#include "config/include/esphw/candy-signals.c"
#include "config/include/esphw/gina-signals.c"
