/**

  @file    buster.h
  @brief   Shared top header file for Buster app.
  @author  Pekka Lehtikoski
  @version 1.0
  @date    2.8.2020

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/
#include "iodevice.h"

/* Include IO pin and communication configuration headers generated by "config" JSON files.
 */
#include "json_io_config.h"

using IoDevice::AbstractApplication;
using IoDevice::AbstractSlaveDevice;
using IoDevice::AbstractSequence;

/* Include application headers.
 */
#include "minion.h"
#include "blink_sequence.h"
#include "application.h"
