/**

  @file    config.c
  @brief   Include and compile automatically generated C code.
  @author  Pekka Lehtikoski
  @version 1.0
  @date    2.8.2020

  Include IO pin and communication configuration code generated by scripts.

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/

/* Global signals. This allows mapping IO pins directly to signals from JSON, but we can have only
   one application instance.
 */
struct buster_t;
extern struct buster_t buster;

#include "json_io_config.c"
