/**

  @file    config.c
  @brief   Uno IO board example featuring  IoT device.
  @author  Pekka Lehtikoski, Markku Nissinen
  @version 1.0
  @date    6.4.2020

  Include IO pin and communication configuration code generated by scripts.

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/
/* Include IO pin and communication configuration headers generated by "config" JSON files.
 */
#include "json_io_config.c"
