/**

  @file    config.c
  @brief   Include singal and pin configuration to build Arduino Uno IO board as IOCOM device.
  @author  Pekka Lehtikoski, Markku Nissinen
  @version 1.0
  @date    22.1.2021

  Include IO pin and communication configuration code generated by scripts from JSON 
  configuration files.

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/

/* Include IO pin and communication configuration headers generated by "config" JSON files.
 */
#include "json_io_config.c"
