/**

  @file    uno.h
  @brief   Arduino Uno IO board as IOCOM device.
  @author  Pekka Lehtikoski, Markku Nissinen
  @version 1.0
  @date    22.1.2021

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/
#define IOCOM_IOBOARD
#include "iocom.h"
#include "pinsx.h"

/* Include IO pin and communication configuration headers generated by "config" JSON files.
 */
#include "json_io_config.h"

/* Function prototypes here, just to keep uno.cpp more readable.
 */
void ioboard_callback(
    struct iocHandle *mblk,
    os_int start_addr,
    os_int end_addr,
    os_ushort flags,
    void *context);
