/* This file is generated by signals_to_c.py script, do not modify. */
#ifndef IOC_SIGNALS_INCLUDED
#define IOC_SIGNALS_INCLUDED
OSAL_C_HEADER_BEGINS

typedef struct candy_t
{
  struct 
  {
    iocMblkSignalHdr hdr;
    iocSignal ambient;
    iocSignal unused_pin;
    iocSignal prm_resolution;
  }
  exp;

  struct 
  {
    iocMblkSignalHdr hdr;
    iocSignal on;
    iocSignal headlight;
    iocSignal set_resolution;
  }
  imp;
}
candy_t;

#define CANDY_EXP_MBLK_SZ 32
#define CANDY_IMP_MBLK_SZ 32

extern OS_FLASH_MEM_H candy_t candy;
extern OS_FLASH_MEM_H iocDeviceHdr candy_hdr;


/* Array length defines. */
#define CANDY_EXP_PRM_RESOLUTION_ARRAY_SZ 10
#define CANDY_IMP_SET_RESOLUTION_ARRAY_SZ 10

/* Defines to check in code with #ifdef to know if signal is configured in JSON. */
#define CANDY_EXP_AMBIENT
#define CANDY_EXP_UNUSED_PIN
#define CANDY_EXP_PRM_RESOLUTION
#define CANDY_IMP_ON
#define CANDY_IMP_HEADLIGHT
#define CANDY_IMP_SET_RESOLUTION

#ifndef IOBOARD_DEVICE_NAME
#define IOBOARD_DEVICE_NAME "candy"
#endif

OSAL_C_HEADER_ENDS
#endif
