/* This file is generated by signals_to_c.py script, do not modify. */
OS_FLASH_MEM struct candy_t candy = 
{
  {
    {"exp", &ioboard_exp, 3, CANDY_EXP_MBLK_SZ, (iocSignal*)&candy.exp.ambient},
    {0, 1, OS_UINT, &ioboard_exp, OS_NULL}, /* ambient */
    {5, 1, OS_UINT, &ioboard_exp, OS_NULL}, /* unused_pin */
    {10, 10, OS_STR, &ioboard_exp, OS_NULL} /* prm_resolution */
  },

  {
    {"imp", &ioboard_imp, 3, CANDY_IMP_MBLK_SZ, (iocSignal*)&candy.imp.on},
    {0, 1, OS_BOOLEAN, &ioboard_imp, OS_NULL}, /* on */
    {1, 1, OS_UINT, &ioboard_imp, OS_NULL}, /* headlight */
    {6, 10, OS_STR, &ioboard_imp, OS_NULL} /* set_resolution */
  }
};

static OS_FLASH_MEM iocMblkSignalHdr * OS_FLASH_MEM candy_mblk_list[] =
{
  &candy.exp.hdr,
  &candy.imp.hdr
};

OS_FLASH_MEM iocDeviceHdr candy_hdr = {(iocMblkSignalHdr**)candy_mblk_list, sizeof(candy_mblk_list)/sizeof(iocMblkSignalHdr*)};
