/**

  @file    controller_config.c
  @brief   Include and compile automatically generated C code.
  @author  Pekka Lehtikoski
  @version 1.0
  @date    30.4.2020

  Include IO pin and communication configuration code generated by scripts.

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/
#include "iocom.h"
#include "signals.h"
#include "info-mblk-binary.h"
#include "network-defaults.h"
#include "gina-for-tito.h"

#include "signals.c"
#include "info-mblk-binary.c"
#include "network-defaults.c"
#include "gina-for-tito.c"

