/**

  @file    controller_main.h
  @brief   Program entry point, Tito IO controller set up.
  @author  Pekka Lehtikoski
  @version 1.0
  @date    30.4.2020

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/

/* Do we need pins library (0/1).
 */
#define PINS_LIBRARY 1

#include "iocom.h"
#include "nodeconf.h"
#include "ioserver.h"
#include "lighthouse.h"
#include "pinsx.h"

/* Include IO pin and communication configuration headers generated by "config" JSON files.
 */
#include "json_io_config.h"

/* Include application headers.
 */
#include "iodevice_base_class.h"
#include "app_iodevice_gina.h"
#include "app_iodevice_candy.h"
#include "sequence_base_class.h"
#include "app_seq_blink_led.h"
#include "application_root.h"

/* IOCOM root object for this program.
 */
extern iocRoot iocom_root;
