/* This file is gerated by generate_c_code.py script, do not modify. */
#define IOCOM_IOBOARD
#include "iocom.h"
#include "pinsx.h"
#include "signals.h"
#include "info-mblk.h"
#include "pins-io.h"
#include "network-defaults.h"
#include "candy-signals.h"
#include "gina-signals.h"
#include "signals.c"
#include "info-mblk.c"
#include "pins-io.c"
#include "network-defaults.c"
#include "candy-signals.c"
#include "gina-signals.c"
