/* This file is gerated by generate_c_code.py script, do not modify. */
#define IOCOM_IOBOARD
#include "iocom.h"
#include "pinsx.h"
#include "config/include/megahw/signals.h"
#include "config/include/megahw/signals-info-mblk.h"
#include "config/include/megahw/pins-io.h"
#include "config/include/megahw/network_defaults.h"
#include "config/include/megahw/candy-signals.h"
#include "config/include/megahw/gina-signals.h"
#include "config/include/megahw/signals.c"
#include "config/include/megahw/signals-info-mblk.c"
#include "config/include/megahw/pins-io.c"
#include "config/include/megahw/network_defaults.c"
#include "config/include/megahw/candy-signals.c"
#include "config/include/megahw/gina-signals.c"
