/**

  @file    config.c
  @brief   Candy camera IO example.
  @author  Pekka Lehtikoski
  @version 1.1
  @date    12.5.2020

  Include IO pin and communication configuration code generated by scripts.

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/
#include "json_io_config.c"
