/**

  @file    config.c
  @brief   Gina IO board example featuring  IoT device.
  @author  Pekka Lehtikoski
  @version 1.0
  @date    8.1.2020

  Include IO pin and communication configuration code generated by scripts.

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/
#include "gina.h"

#include "pins-io.c"
#include "signals.c"
#include "info-mblk.c"
#include "network-defaults.c"

