/* This file is generated by parameters_to_c.py script, do not modify. */
#ifndef IOC_PARAMETERS_INCLUDED
#define IOC_PARAMETERS_INCLUDED
OSAL_C_HEADER_BEGINS

struct candy_t;
void ioc_initialize_candy_parameters(const struct candy_t *sigs, os_int block_nr, void *reserved);
osalStatus ioc_load_candy_parameters(const struct candy_t *sigs);
osalStatus ioc_save_candy_parameters(const struct candy_t *sigs);
osalStatus ioc_autosave_candy_parameters(const struct candy_t *sigs);

OSAL_C_HEADER_ENDS
#endif
