/* This file is generated by parameters_to_c.py script, do not modify. */
typedef struct iocParameterStorage
{
  os_int block_nr;
  os_boolean changed;
  os_timer ti;
}
iocParameterStorage;
static iocParameterStorage ioc_prm_storage;
typedef struct iocDevicePersistentPrm {
};

void ioc_initialize_parameters(os_int block_nr)
{
  os_memclear(&ioc_prm_storage, sizeof(ioc_prm_storage));
  ioc_prm_storage.block_nr = block_nr;
  ioc_set_str(&candy.exp.size, "320x240");
  ioc_set(&candy.exp.quality, 40);
  ioc_set(&candy.exp.brightness, 50);
  ioc_set(&candy.exp.contrast, 50);
  ioc_set(&candy.exp.hue, 50);
  ioc_set(&candy.exp.saturation, 50);
  ioc_set(&candy.exp.on, 1);
};

iosStatus ioc_load_parameters(void)
{
  return OSAL_SUCCESS;
};

iosStatus ioc_save_parameters(void)
{
  return OSAL_SUCCESS;
};

iosStatus ioc_autosave_parameters(void)
{
  if (ioc_prm_storage.changed) {
    if (os_has_elapsed(&ioc_prm_storage.ti, 10000)) {
       ioc_save_parameters();
    }
  }
  return OSAL_SUCCESS;
};

