/* This file is generated by parameters_to_c.py script, do not modify. */
void ioc_initialize_parameters(os_int block_nr)
{
  os_memclear(&ioc_prm_storage, sizeof(ioc_prm_storage));
  ioc_prm_storage.block_nr = block_nr;
  ioc_set_str(&candy.exp.size, "320x240");
  ioc_set(&candy.exp.quality, 40);
  ioc_set(&candy.exp.brightness, 50);
  ioc_set(&candy.exp.contrast, 50);
  ioc_set(&candy.exp.hue, 50);
  ioc_set(&candy.exp.saturation, 50);
  ioc_set(&candy.exp.on, 1);
};

osalStatus ioc_load_parameters(void)
{
  os_char buf[21];
  osalStatus s;

  s = os_load_persistent(ioc_prm_storage.block_nr, buf, sizeof(buf));
  if (!OSAL_IS_ERROR(s)) {
    ioc_write(candy.exp.size.handle, candy.exp.size.addr, buf + 0, 11, 0);
    ioc_write(candy.exp.quality.handle, candy.exp.quality.addr, buf + 11, 2, 0);
    ioc_write(candy.exp.brightness.handle, candy.exp.brightness.addr, buf + 13, 2, 0);
    ioc_write(candy.exp.contrast.handle, candy.exp.contrast.addr, buf + 15, 2, 0);
    ioc_write(candy.exp.hue.handle, candy.exp.hue.addr, buf + 17, 2, 0);
    ioc_write(candy.exp.saturation.handle, candy.exp.saturation.addr, buf + 19, 2, 0);
  }
  return s;
};

osalStatus ioc_save_parameters(void)
{
#if OSAL_PERSISTENT_SUPPORT
  os_char buf[21];
  osalStatus s;

  ioc_read(candy.exp.size.handle, candy.exp.size.addr, buf + 0, 11, 0);
  ioc_read(candy.exp.quality.handle, candy.exp.quality.addr, buf + 11, 2, 0);
  ioc_read(candy.exp.brightness.handle, candy.exp.brightness.addr, buf + 13, 2, 0);
  ioc_read(candy.exp.contrast.handle, candy.exp.contrast.addr, buf + 15, 2, 0);
  ioc_read(candy.exp.hue.handle, candy.exp.hue.addr, buf + 17, 2, 0);
  ioc_read(candy.exp.saturation.handle, candy.exp.saturation.addr, buf + 19, 2, 0);
  s = os_save_persistent(ioc_prm_storage.block_nr, buf, sizeof(buf), OS_FALSE);
  return s;
#else
  return OSAL_STATUS_NOT_SUPPORTED;
#endif
};

osalStatus ioc_autosave_parameters(void)
{
#if OSAL_PERSISTENT_SUPPORT
  if (ioc_prm_storage.changed) {
    if (os_has_elapsed(&ioc_prm_storage.ti, 10000)) {
       ioc_save_parameters();
    }
  }
  return OSAL_SUCCESS;
#else
  return OSAL_STATUS_NOT_SUPPORTED;
#endif
};

