/* This file is generated by parameters_to_c.py script, do not modify. */
iocDevicePersistentPrm ioc_persistent_prm = {;
  "320x240" /* size */,
  40 /* quality */,
  50 /* brightness */,
  50 /* contrast */,
  50 /* hue */,
  50 /* saturation */};

iocDeviceVolatilePrm ioc_volatile_prm = {;
  1 /* on */};

