/* This file is generated by parameters_to_c.py script, do not modify. */
#ifndef IOC_PARAMETERS_INCLUDED
#define IOC_PARAMETERS_INCLUDED
OSAL_C_HEADER_BEGINS

void ioc_initialize_parameters(os_int block_nr);
osalStatus ioc_load_parameters(void);
osalStatus ioc_save_parameters(void);
osalStatus ioc_autosave_parameters(void);

OSAL_C_HEADER_ENDS
#endif
