/**

  @file    app_config.c
  @brief   Compile automatically generated C code.
  @author  Pekka Lehtikoski
  @version 1.0
  @date    15.1.2020

  Include communication configuration code generated by script from json definitions.

  Copyright 2020 Pekka Lehtikoski. This file is part of the iocom project and shall only be used,
  modified, and distributed under the terms of the project licensing. By continuing to use, modify,
  or distribute this file you indicate that you have read the license and understand and accept
  it fully.

****************************************************************************************************
*/
#include "json_io_config.c"
