# parameters_to_c.py 11.6.2020/pekka
# Convert parameter JSON file to C code.
import json
import os
import sys

# Size excludes signal state byte.
osal_typeinfo = {
    "undef" : 0,
    "boolean" : 1,
    "char" : 1,
    "uchar" : 1,
    "short" : 2,
    "ushort" : 2,
    "int" : 4,
    "uint" : 4,
    "int64" : 8,
    "long" : 8,
    "float" : 4,
    "double" : 8,
    "dec01" : 2,
    "dec001" : 2,
    "str" : 1,
    "object" : 0,
    "pointer" : 0}


def start_c_files():
    global ccontent, hcontent, hfilepath
    ccontent = '/* This file is generated by parameters_to_c.py script, do not modify. */\n'
    hcontent = '/* This file is generated by parameters_to_c.py script, do not modify. */\n'
    path, fname = os.path.split(hfilepath)
    fname, ext = os.path.splitext(fname)
    macroname = 'IOC_' + fname.upper() + '_INCLUDED'
    hcontent += '#ifndef ' + macroname + '\n'
    hcontent += '#define ' + macroname + '\n'
    hcontent += 'OSAL_C_HEADER_BEGINS\n\n'

def finish_c_files():
    global ccontent, hcontent
    hcontent += '\nOSAL_C_HEADER_ENDS\n'
    hcontent += '#endif\n'

def calc_signal_memory_sz(type, array_n):
    if type == "boolean":
        if array_n <= 1:
            return 1
        else:
            return ((array_n + 7) >> 3) + 1

    type_sz = osal_typeinfo[type];
    return array_n * type_sz + 1

# Set address and type, if not set
def set_offset_and_type(parameter):
    global current_type, current_offset

    type = parameter.get('type', None)
    if type != None:
        current_type = type
    else:
        parameter['type'] = current_type

    array_n = parameter.get('array', 1)
    if array_n < 1:
        array_n = 1

    mem_sz_bytes = calc_signal_memory_sz(current_type, array_n)
    parameter['my_offset'] = current_offset
    parameter['my_bytes'] = mem_sz_bytes

    current_offset += mem_sz_bytes


def append_init_parameter_to_c(parameter):
    global ccontent, hcontent
 
    init = parameter.get('init', None);
    if init == None:
        return;

    name = parameter.get("name", None);
    if name == None:
        print("Parameter without name");
        return

    type = parameter["type"]
    array_n = parameter.get('array', 1);

    ccontent += '  '

    if array_n > 1:
        if type == 'str':
            ccontent += 'ioc_set_str(&sigs->.exp.' + name + ', "' + str(init) + '");\n'
        else:
            ccontent += 'static OS_CONST os_' + type + ' ioc_idata_' + name + '[] = {'
            init_list = init.split(',')
            is_first = True
            for i in init_list:
                if not is_first:
                    ccontent += ', '
                is_first = False
                ccontent += str(i)
            ccontent += '};\n  '
            ccontent += 'ioc_set_array(&sigs->exp.' + name + ', ' + 'ioc_idata_' + name + ');\n'
    else:
        ccontent += 'ioc_set(&sigs->exp.' + name + ', ' + str(init) + ');\n'


def append_load_parameter_to_c(parameter):
    global ccontent

    name = parameter.get("name", None);
    if name == None:
        return

    dsig ='sigs->exp.' + name
    ccontent += '    ioc_write(' + dsig + '.handle, ' + dsig + '.addr, buf + ' + str(parameter['my_offset']) + ', ' + str(parameter['my_bytes']) + ', 0);\n'

def append_save_parameter_to_c(parameter):
    global ccontent
    
    name = parameter.get("name", None);
    if name == None:
        return

    dsig = 'sigs->exp.' + name
    ccontent += '  ioc_read(' + dsig + '.handle, ' + dsig + '.addr, buf + ' + str(parameter['my_offset']) + ', ' + str(parameter['my_bytes']) + ', 0);\n'

def process_struct(step, data):
    global current_type, current_offset, persistent_struct_sz

    is_first = True
    current_type = "ushort"
    current_offset = 0

    current_type = "ushort"
    title = data.get("title", "untitled")
    groups = data.get("groups", None)
    if groups == None:
        print('"' + title + '" is empty?')
        return

    for group in groups:
        parameters = group.get("parameters", None)
        if parameters == None:
            print("Group without parameters?")
        elif step == 'setoffsets':
            for parameter in parameters:
                set_offset_and_type(parameter)
        elif step == 'init':
            for parameter in parameters:
                append_init_parameter_to_c(parameter)
        elif step == 'load':
            for parameter in parameters:
                append_load_parameter_to_c(parameter)
        elif step == 'save':
            for parameter in parameters:
                append_save_parameter_to_c(parameter)

    if step == 'setoffsets':
        persistent_struct_sz = current_offset

def process_source_data(step, sourcedata):
    for data in sourcedata:
        persistent = data.get("persistent", None)
        if persistent != None:
            process_struct(step, persistent)

        if step == 'init':
            volatile = data.get("volatile", None)
            if volatile != None:
                process_struct(step, volatile)

def load_source_file(path):
    global device_name
    read_file = open(path, "r")
    if read_file:
        data = json.load(read_file)

        if device_name == None:
            device_name = data.get("name", "NONAME")
    return data;

# Write a file only if content has changed
def write_file_only_if_changed(filepath, content):
    if (os.path.isfile(filepath)):
        hfile = open(filepath, "r")
        old_content = hfile.read()
        hfile.close()
        if (content == old_content):
            return

    print("Writing parameters_to_c file " + filepath)

    hfile = open(filepath, "w")
    hfile.write(content)
    hfile.close()
    return

def mymain():
    global ccontent, hcontent
    global cfilepath, hfilepath, device_name
    n = len(sys.argv)
    sourcefiles = []
    outpath = None
    expect = None
    device_name = None
    for i in range(1, n):
        if sys.argv[i][0] == "-":
            if sys.argv[i][1] == "o":
                expect = 'o'
        else:
            if expect=='o':
                outpath = sys.argv[i]
                expect = None
            else:
                sourcefiles.append(sys.argv[i])

    if len(sourcefiles) < 1:
        print("No source files")
        exit()
        # sourcefiles.append('/coderoot/iocom/examples/candy/config/parameters/parameters.json')

    if outpath is None:
        outpath = sourcefiles[0]

    filename, file_extension = os.path.splitext(outpath)
    cfilepath = filename + '.c'
    hfilepath = filename + '.h'

    # Make sure that "intermediate" directory exists.
    dir_path, file_name =  os.path.split(outpath)
    try:
        os.makedirs(dir_path)
    except FileExistsError:
        pass

    sourcedata = []
    for path in sourcefiles:
        data = load_source_file(path)
        sourcedata.append(data)

    # print("Writing PRM files " + cfilepath + " and " + hfilepath)

    start_c_files()

    # Set offset, size in bytes and type for every parameter
    # and structure sizes for volatile and persistent parameters.
    process_source_data('setoffsets', sourcedata)
    
    # Write initialization function, set offset and size for 
    ccontent += 'void ioc_initialize_' + device_name + '_parameters(const struct ' + device_name + '_t *sigs, os_int block_nr, void *reserved)\n{\n'
    ccontent += '  os_memclear(&ioc_prm_storage, sizeof(ioc_prm_storage));\n'
    ccontent += '  ioc_prm_storage.block_nr = block_nr;\n'
    process_source_data('init', sourcedata)
    ccontent += '}\n\n'

    # Write persistent load function
    ccontent += 'osalStatus ioc_load_' + device_name + '_parameters(const struct ' + device_name + '_t *sigs)\n{\n'
    ccontent += '#if OSAL_PERSISTENT_SUPPORT\n'
    ccontent += '  os_char buf[' + str(persistent_struct_sz) + '];\n'
    ccontent += '  osalStatus s;\n\n'
    ccontent += '  ioc_prm_storage.changed = OS_FALSE;\n'
    ccontent += '  s = os_load_persistent(ioc_prm_storage.block_nr, buf, sizeof(buf));\n'
    ccontent += '  if (!OSAL_IS_ERROR(s)) {\n'
    process_source_data('load', sourcedata)
    ccontent += '  }\n'
    ccontent += '  return s;\n'
    ccontent += '#else\n'
    ccontent += '  return OSAL_STATUS_NOT_SUPPORTED;\n'
    ccontent += '#endif\n'
    ccontent += '}\n\n'

    # Write persistent save function
    ccontent += 'osalStatus ioc_save_' + device_name + '_parameters(const struct ' + device_name + '_t *sigs)\n{\n'
    ccontent += '#if OSAL_PERSISTENT_SUPPORT\n'
    ccontent += '  os_char buf[' + str(persistent_struct_sz) + '];\n'
    ccontent += '  osalStatus s;\n\n'
    process_source_data('save', sourcedata)
    ccontent += '  s = os_save_persistent(ioc_prm_storage.block_nr, buf, sizeof(buf), OS_FALSE);\n'
    ccontent += '  ioc_prm_storage.changed = OS_FALSE;\n'
    ccontent += '  return s;\n'
    ccontent += '#else\n'
    ccontent += '  return OSAL_STATUS_NOT_SUPPORTED;\n'
    ccontent += '#endif\n'
    ccontent += '}\n\n'

    # Write autosave function
    ccontent += 'osalStatus ioc_autosave_' + device_name + '_parameters(const struct ' + device_name + '_t *sigs)\n{\n'
    ccontent += '#if OSAL_PERSISTENT_SUPPORT\n'
    ccontent += '  if (ioc_prm_storage.changed) {\n'
    ccontent += '    if (os_has_elapsed(&ioc_prm_storage.ti, 3000)) {\n'
    ccontent += '       ioc_save_' + device_name + '_parameters(sigs);\n'
    ccontent += '    }\n'
    ccontent += '  }\n'
    ccontent += '  return OSAL_SUCCESS;\n'
    ccontent += '#else\n'
    ccontent += '  return OSAL_STATUS_NOT_SUPPORTED;\n'
    ccontent += '#endif\n'
    ccontent += '}\n\n'

    # Write heade file
    hcontent += 'struct ' + device_name + '_t;\n'
    hcontent += 'void ioc_initialize_' + device_name + '_parameters(const struct ' + device_name + '_t *sigs, os_int block_nr, void *reserved);\n'
    hcontent += 'osalStatus ioc_load_' + device_name + '_parameters(const struct ' + device_name + '_t *sigs);\n'
    hcontent += 'osalStatus ioc_save_' + device_name + '_parameters(const struct ' + device_name + '_t *sigs);\n'
    hcontent += 'osalStatus ioc_autosave_' + device_name + '_parameters(const struct ' + device_name + '_t *sigs);\n'

    finish_c_files()

    write_file_only_if_changed(cfilepath, ccontent)
    write_file_only_if_changed(hfilepath, hcontent)

mymain()
