# signals-to_c.py 26.4.2021/pekka
# Converts communication signal map written in JSON to C source and header files.
import json
import os
import sys
import re

IOC_SIGNAL_NAME_SZ = 32
IOC_NAME_SZ = 16
IOC_PIN_NAME_SZ = 64
IOC_PIN_GROUP_NAME_SZ = 64

# Size excludes signal state byte.
osal_typeinfo = {
    "undef" : 0,
    "boolean" : 1,
    "char" : 1,
    "uchar" : 1,
    "short" : 2,
    "ushort" : 2,
    "int" : 4,
    "uint" : 4,
    "int64" : 8,
    "long" : 8,
    "float" : 4,
    "double" : 8,
    "dec01" : 2,
    "dec001" : 2,
    "str" : 1,
    "object" : 0,
    "pointer" : 0}

def check_valid_name(label, name, sz, allow_numbers):
    if name == None:
        all_failed(label + " name is not defined.")

    if len(name) >= sz:
        all_failed(label + " name '" + name + "' is too long. Maximum is " + str(sz - 1) + "characters.")

    if allow_numbers:
        if not re.match(r'^[A-Za-z0-9_]+$', name):
            all_failed(label + " name '" + name + "' may contain only characters 'A' - 'Z', 'a' - 'z', '0' -'9' and underscore '_'.")
    else:
        if not re.match(r'^[A-Za-z_]+$', name):
            all_failed(label + " name '" + name + "' may contain only characters 'A' - 'Z', 'a' - 'z', and underscore '_'.")

def all_failed(message):
    global ccontent, hcontent
    print(message)
    ccontent += "FAILED: " + message
    hcontent += "FAILED: " + message
    finish_c_files()
    exit()

def start_c_files():
    global ccontent, hcontent, hfilepath
    ccontent = '/* This file is generated by signals_to_c.py script, do not modify. */\n'
    hcontent = '/* This file is generated by signals_to_c.py script, do not modify. */\n'
    path, fname = os.path.split(hfilepath)
    fname, ext = os.path.splitext(fname)
    macroname = 'IOC_' + fname.upper() + '_INCLUDED'
    hcontent += '#ifndef ' + macroname + '\n'
    hcontent += '#define ' + macroname + '\n'
    hcontent += 'OSAL_C_HEADER_BEGINS\n\n'

def finish_c_files():
    global ccontent, hcontent
    hcontent += '\nOSAL_C_HEADER_ENDS\n'
    hcontent += '#endif\n'

def write_signal_to_c_header(signal_name):
    global hcontent
    hcontent += "    iocSignal " + signal_name + ";\n"

def calc_signal_memory_sz(type, array_n):
    if type == "boolean":
        if array_n <= 1:
            return 1
        else:
            return ((array_n + 7) >> 3) + 1

    type_sz = osal_typeinfo[type]
    return array_n * type_sz + 1

def write_signal_to_c_source_for_iodevice(signal_name, signal):
    global ccontent, hcontent, array_list, signal_list
    global max_addr, signal_nr, nro_signals, handle, pinlist

    addr = signal['addr']
    type = signal['type']
    array_n = signal.get('array', 1)
    if array_n < 1:
        array_n = 1

    sname = device_name + '_' + block_name + '_' + signal_name
    signal_list.append('#define ' + sname.upper())
    if array_n > 1:
        arr_name = sname.upper() + '_ARRAY_SZ'
        array_list.append('#define ' + arr_name + ' ' + str(array_n))

    my_name = device_name + '.' + block_name + '.' + signal_name

    if signal_nr == 1:
        ccontent += '\n  {\n    {"' + block_name + '", ' + handle + ', ' + str(nro_signals) + ', '
        define_name = device_name + '_' + block_name + "_MBLK_SZ"
        ccontent += define_name.upper() + ', '
        ccontent += '(iocSignal*)&' + my_name + '},\n'

    ccontent += '    {'

    ccontent += str(addr) + ", "
    ccontent += str(array_n) + ", "
    ccontent += 'OS_' + type.upper()
    if signal_name in pinlist:
        ccontent += '|IOC_PIN_PTR'
    else:
        pflag = signal.get('pflag', 0)
        if pflag & 64:
            ccontent += '|IOC_PFLAG_IS_PRM'
        if pflag & 128:
            ccontent += '|IOC_PFLAG_IS_PERSISTENT'

    ccontent += ', ' + handle

    paddr = signal.get('paddr', None)
    if signal_name in pinlist:
        ccontent += ', ' + pinlist[signal_name]
    elif paddr != None:
        ccontent += ', ' + paddr
    else:
        ccontent += ', OS_NULL'

    ccontent += '}'

    if signal_nr < nro_signals:
        ccontent += ','

    signal_nr = signal_nr + 1
    ccontent += ' /* ' + signal_name + ' */\n'

def write_signal_to_c_source_for_controller(signal_name, signal):
    global ccontent, hcontent, array_list, signal_list
    global max_addr, signal_nr, nro_signals, handle, pinlist

    addr = signal['addr']
    type = signal['type']
    array_n = signal.get('array', 1)
    if array_n < 1:
        array_n = 1

    sname = device_name + '_' + block_name + '_' + signal_name
    signal_list.append('#define ' + sname.upper())
    if array_n > 1  and not is_dynamic:
        arr_name = sname.upper() + '_ARRAY_SZ'
        array_list.append('#define ' + arr_name + ' ' + str(array_n))

    if signal_nr == 1:
        my_name = '  s->' + block_name + '.hdr'
        ccontent += my_name + '.mblk_name = "' + block_name + '";\n'
        ccontent += my_name + '.n_signals = ' + str(nro_signals)  + ';\n'
        if not is_dynamic:
            define_name = device_name + '_' + block_name + "_MBLK_SZ"
            ccontent += my_name + '.mblk_sz = ' + define_name.upper() + ';\n'
        ccontent += my_name + '.first_signal = &s->' + block_name + '.' + signal_name + ';\n'

    ccontent += '\n /* ' + signal_name + ' */\n'
    my_name = '  s->' + block_name + '.' + signal_name
    if not is_dynamic:
        ccontent += my_name + '.addr = ' + str(addr) + ';\n'
        ccontent += my_name + '.n = ' + str(array_n) + ';\n'

        my_flags = 'OS_' + type.upper()
        if not is_dynamic:
            if signal_name in pinlist:
                my_flags += '|IOC_PIN_PTR'
                ccontent += my_name + '.ptr = ' + pinlist[signal_name] + ';\n'

            elif not is_slave_device:
                pflag = signal.get('pflag', 0)
                if pflag & 64:
                    my_flags += '|IOC_PFLAG_IS_PRM'
                if pflag & 128:
                    my_flags += '|IOC_PFLAG_IS_PERSISTENT'

                if pflag & 192:
                    paddr = signal.get('paddr', None)
                    if paddr != None:
                        ccontent += my_name + '.ptr = ' + paddr + ';\n'


        ccontent += my_name + '.flags = ' + my_flags + ';\n'

    if is_dynamic:
        ccontent += my_name + '.ptr = \"' + signal_name + '\";\n'

    signal_nr = signal_nr + 1

def process_signal(signal):
    global block_name
    signal_name = signal.get("name", None)
    if signal_name == None:
        all_failed("'name' not found for signal in '" + block_name + "'")

    check_valid_name("Signal", signal_name, IOC_SIGNAL_NAME_SZ, True)

    write_signal_to_c_header(signal_name)
    if is_controller:
        write_signal_to_c_source_for_controller(signal_name, signal)
    else:
        write_signal_to_c_source_for_iodevice(signal_name, signal)

def check_if_duplicates(mylist):
    return len(mylist) != len(set(mylist))

def write_my_error(msg):
    global cfile
    print(msg)
    ccontent += '\n\n***************************************\n' + msg + '\n***************************************\n\n'

def process_mblk(mblk):
    global ccontent, hcontent, reserved_addrs
    global block_name, handle, define_list, mblk_nr, nro_mblks, mblk_list
    global max_addr, signal_nr, nro_signals, is_controller

    block_name = mblk.get("name", "MBLK")
    check_valid_name("Memory block", block_name, IOC_NAME_SZ, True)
    handle = mblk.get("handle", "OS_NULL")
    if handle == "OS_NULL":
        handle = "&ioboard_" + block_name

    signals = mblk.get("signals", None)
    if signals == None:
        all_failed("'signals' not found for " + block_name)

    mblk_list.append(device_name + '.' + block_name)

    signal_nr = 1
    nro_signals = len(signals)
    max_addr = mblk['max_addr']

    hcontent += '\n  struct ' + '\n  {\n'
    hcontent += '    iocMblkSignalHdr hdr;\n'

    for signal in signals:
        process_signal(signal)

    hcontent += '  }\n  ' + block_name + ';\n'
    if not is_dynamic:
        define_name = device_name + '_' + block_name + "_MBLK_SZ"
        define_list.append("#define " + define_name.upper() + " " + str(max_addr) + "\n")

    if not is_controller:
        ccontent += '  }'
        if mblk_nr < nro_mblks:
            ccontent += ',\n'
    else:
        ccontent += '  s->mblk_list[' + str(mblk_nr - 1) + '] = &s->' + block_name + '.hdr;\n\n'

    if check_if_duplicates(reserved_addrs):
        write_my_error('ERROR: Duplicated signal addressess found in JSON!')

    mblk_nr = mblk_nr + 1

def write_assembly_item(prefix, ending, assembly_name):
    global ccontent, is_controller, device_name
    if is_controller:
        ccontent += '  s->' + assembly_name + '.' + ending + ' =  &s->' + prefix + ending + ';\n'
    else:
        ccontent += '&' + device_name + '.' + prefix + ending + ',\n   '

def process_assembly(assembly):
    global ccontent, hcontent, is_controller
    assembly_name = assembly.get("name", None)
    check_valid_name("Assembly", assembly_name, IOC_NAME_SZ, True)
    assembly_type = assembly.get("type", None)
    check_valid_name("Assembly type", assembly_type, IOC_NAME_SZ, True)

    if assembly_type == 'lcam_ring' or assembly_type == 'cam_ring':
        imp = assembly.get("imp", "imp.undefined_*")
        exp = assembly.get("exp", "exp.undefined_*")

        hcontent += '\n  iocStreamerSignals ' + assembly_name + ';\n'

        if is_controller:
            ccontent += '\n /* ' + assembly_type + " '" + assembly_name + "' */\n"
        else:
            ccontent += ',\n\n  /* Signals for ' + assembly_type + " '" + assembly_name + "' */\n  {"
        write_assembly_item(imp, "cmd", assembly_name)
        write_assembly_item(imp, "select", assembly_name)
        write_assembly_item(exp, "err", assembly_name)
        write_assembly_item(exp, "cs", assembly_name)
        write_assembly_item(exp, "buf", assembly_name)
        write_assembly_item(exp, "head", assembly_name)
        write_assembly_item(imp, "tail", assembly_name)
        write_assembly_item(exp, "state", assembly_name)
        if not is_controller:
            ccontent += 'OS_FALSE, OS_FALSE}'

    elif assembly_type == 'lcam_flat' or assembly_type == 'cam_flat':
        imp = assembly.get("imp", "imp.undefined_*")
        exp = assembly.get("exp", "exp.undefined_*")

        hcontent += '\n  iocStreamerSignals ' + assembly_name + ';\n'

        if is_controller:
            ccontent += '\n /* ' + assembly_type + " '" + assembly_name + "' */\n"
        else:
            ccontent += ',\n\n  /* Signals for ' + assembly_type + " '" + assembly_name + "' */\n  {"
        write_assembly_item(imp, "cmd", assembly_name)
        if not is_controller:
            ccontent += 'OS_NULL, '
        write_assembly_item(exp, "err", assembly_name)
        write_assembly_item(exp, "cs", assembly_name)
        write_assembly_item(exp, "buf", assembly_name)
        write_assembly_item(exp, "head", assembly_name)
        if not is_controller:
            ccontent += 'OS_NULL, '
        write_assembly_item(exp, "state", assembly_name)
        if not is_controller:
            ccontent += 'OS_FALSE, OS_TRUE}'

        else:
            ccontent += '  s->' + assembly_name + '.flat_buffer = OS_TRUE;\n'

    else:
        ccontent += "\n /* Assembly '" + assembly_name + "' type '" + assembly_type + "' generates no code */\n"

# Preprocess signal
# Assign addresses to signal
def preprocess_signal(p_signals, signal):
    global current_type, current_addr, max_addr, reserved_addrs, device_name

    addr = signal.get('addr', None)
    if addr != None:
        current_addr = addr

    p_signal = {}
    p_signals[current_addr] = p_signal
    p_signal['addr'] = current_addr

    type = signal.get('type', None)
    if type != None:
        current_type = type
    p_signal['type'] = current_type

    array_n = signal.get('array', 1)
    if array_n < 1:
        array_n = 1

    mem_sz_bytes = calc_signal_memory_sz(current_type, array_n)
    reserved_addrs += list(range(current_addr, current_addr + mem_sz_bytes))

    current_addr += mem_sz_bytes
    if current_addr > max_addr:
        max_addr = current_addr

    for key in signal:
        if p_signal.get(key, None) == None:
            p_signal[key] = signal[key]

    pflag = p_signal.get('pflag', 0)
    if pflag & 64:
        name = p_signal.get('name', "NONAME")
        if name.startswith('set_'):
            p_signal['paddr'] = '&' + device_name + '.exp.' + name[4:]

        else:
            del p_signal['pflag']

# Preprocess memory block
# Remove group layer
# Assign addresses with signals
# Sorts signals by address
def preprocess_mblk(p_mblk, mblk):
    global current_type, current_addr, max_addr, reserved_addrs

    current_type = "ushort"
    current_addr = 0
    max_addr = 24
    reserved_addrs = []

    # Remove group layer and assign addressess to signals.
    for key in mblk:
        if key == 'groups':
            groups  = mblk[key]
            p_signals = {}
            p_mblk['signals'] = p_signals
            for group in groups:
                signals = group.get("signals", None)
                if signals != None:
                    for signal in signals:
                        preprocess_signal(p_signals, signal)

        else:
            p_mblk[key] = mblk[key]

    # Sort signals by address
    unsorted_signals = p_mblk.get('signals', None)
    if unsorted_signals != None:
        sorted_signals = []
        for i in sorted(unsorted_signals):
            sorted_signals.append(unsorted_signals[i])

        p_mblk['signals'] = sorted_signals

    p_mblk['max_addr'] = max_addr

# Preprocess JSON file
# Remove group layer from memory block
# Assign addresses with signals
# Sorts signals by address
def preprocess_json(preprocessed, data):
    for key in data:
        if key == 'mblk':
            mblks = data[key]
            p_mblks = []
            preprocessed[key] = p_mblks
            for mblk in mblks:
                p_mblk = {}
                preprocess_mblk(p_mblk, mblk)
                p_mblks.append(p_mblk)

        else:
            preprocessed[key] = data[key]


def process_source_file(path):
    global ccontent, hcontent, array_list, signal_list
    global device_name, hw, define_list, mblk_nr, nro_mblks, mblk_list
    try:
        read_file = open(path, "r")
    except:
        all_failed("Opening file " + path + " failed")

    data = json.load(read_file)

    if device_name == None:
        device_name = data.get("name", "unnameddevice")

    preprocessed = {}
    preprocess_json(preprocessed, data)
    data = preprocessed

    check_valid_name("Device", device_name, IOC_NAME_SZ, False)

    mblks = data.get("mblk", None)
    if mblks == None:
        all_failed("'mblk' not found")

    mblk_nr = 1
    nro_mblks = len(mblks)

    struct_name = device_name + '_t'
    define_list = []
    hcontent += 'typedef struct ' + struct_name + '\n{'

    if is_controller:
        hcontent += '\n  iocDeviceHdr hdr;\n'
        hcontent += '  iocMblkSignalHdr *mblk_list[' + str(nro_mblks) + '];\n'

        ccontent += 'void ' + device_name + '_init_signal_struct(' + struct_name + ' *s)\n{\n'
        ccontent += '  os_memclear(s, sizeof(' + struct_name + '));\n'

    else:
        ccontent += 'OS_CONST struct ' + struct_name + ' ' + device_name + ' = \n{'

    mblk_list = []
    array_list = []
    signal_list = []

    for mblk in mblks:
        process_mblk(mblk)

    assemblies = data.get("assembly", None)
    if assemblies != None:
        for assembly in assemblies:
            process_assembly(assembly)

    ccontent += '\n'

    if is_controller:
        ccontent += '  s->hdr.n_mblk_hdrs = ' + str(nro_mblks) + ';\n'
        ccontent += '  s->hdr.mblk_hdr = s->mblk_list;\n'
        ccontent += '}\n'
    else:
        ccontent += '};\n'

    hcontent += '}\n' + struct_name + ';\n\n'

    for d in define_list:
        hcontent += d

    if not is_controller:
        hcontent += '\nextern OS_CONST_H ' + struct_name + ' ' + device_name + ';\n'

        ccontent += '\n#if IOC_SIGNAL_RANGE_SUPPORT\n'
        list_name = device_name + "_mblk_list"
        ccontent += 'static OS_CONST iocMblkSignalHdr * OS_CONST ' + list_name + '[] =\n{\n  '
        isfirst = True
        for p in mblk_list:
            if not isfirst:
                ccontent += ',\n  '
            isfirst = False
            ccontent += '&' + p + '.hdr'
        ccontent += '\n};\n'
        ccontent += '#endif\n\n'

        ccontent += '#if IOC_SIGNAL_RANGE_SUPPORT\n'
        ccontent += 'OS_CONST iocDeviceHdr ' + device_name + '_hdr = {(iocMblkSignalHdr**)' + list_name + ', sizeof(' + list_name + ')/' + 'sizeof(iocMblkSignalHdr*)};\n'
        ccontent += '#endif\n'
        hcontent += '#if IOC_SIGNAL_RANGE_SUPPORT\n'
        hcontent += 'extern OS_CONST_H iocDeviceHdr ' + device_name + '_' + 'hdr;\n'
        hcontent += '#endif\n\n'

    else:
        hcontent += '\nvoid ' + device_name + '_init_signal_struct(' + struct_name + ' *s);\n'

    hcontent += '\n/* IO device hardware version. */\n'
    hcontent += '#define ' + device_name.upper() + '_HW \"' + hw + '\"\n'

    if len(array_list) > 0:
        hcontent += '\n/* Array length defines. */\n'
        for p in array_list:
            hcontent += p + '\n'

    if len(signal_list) > 0:
        hcontent += '\n/* Defines to check in code with #ifdef to know if signal is configured in JSON. */\n'
        for p in signal_list:
            hcontent += p + '\n'


def list_pins_rootblock(rootblock):
    global pinlist
    prins_prefix = rootblock.get('prefix', "pins")
    groups = rootblock.get("groups", None)

    for group in groups:
        pins  = group.get("pins", None)
        if pins != None:
            pingroup_name = group.get("name", None)
            check_valid_name("Pin group", pingroup_name, IOC_PIN_GROUP_NAME_SZ, True)
            for pin in pins:
                name = pin.get('name', None)
                check_valid_name("Pin", name, IOC_PIN_NAME_SZ, True)
                if name is not None:
                    pinlist.update({name : '&' + prins_prefix + '.' + pingroup_name + '.' + name})

def list_pins_in_pinsfile(path):
    try:
        pins_file = open(path, "r")
    except:
        all_failed("Opening file " + path + " failed")

    data = json.load(pins_file)
    rootblocks = data.get("io", None)
    if rootblocks == None:
        all_failed("'io' not found")

    for rootblock in rootblocks:
        list_pins_rootblock(rootblock)

# Write a file only if content has changed
def write_file_only_if_changed(filepath, content):
    if (os.path.isfile(filepath)):
        hfile = open(filepath, "r")
        old_content = hfile.read()
        hfile.close()
        if (content == old_content):
            return

    print("Writing signals_to_c file " + filepath)

    hfile = open(filepath, "w")
    hfile.write(content)
    hfile.close()
    return

def mymain():
    global ccontent, hcontent, cfilepath, hfilepath, pinlist, device_name, hw, is_controller, is_dynamic, is_slave_device

    # Get command line arguments
    n = len(sys.argv)
    sourcefiles = []
    outpath = None
    pinspath = None
    expectpath = True
    device_name = None
    hw = 'generic'
    application_type = "iodevice"
    for i in range(1, n):
        if sys.argv[i][0] == "-":
            if sys.argv[i][1] == "o":
                outpath = sys.argv[i+1]
                expectpath = False

            if sys.argv[i][1] == "p":
                pinspath = sys.argv[i+1]
                expectpath = False

            if sys.argv[i][1] == "d":
                device_name = sys.argv[i+1]
                expectpath = False

            if sys.argv[i][1] == "a":
                # application_type:
                #   "iodevice" - IO board, etc
                #   "controller-static" Controller using static addressess and types to match data with IO device
                #   "controller-dynamic" Controller using signal names to match types and
                application_type = sys.argv[i+1]
                expectpath = False

            if sys.argv[i][1] == "h":
                hw = sys.argv[i+1]
                expectpath = False

        else:
            if expectpath:
                sourcefiles.append(sys.argv[i])
            expectpath = True

    if len(sourcefiles) < 1:
        print("No source files")
        exit()

#    sourcefiles.append('/coderoot/iocom/examples/buster/config/intermediate/grumpy/signals-merged.json')
#    outpath = '/coderoot/iocom/examples/buster/config/include/grumpy/signals.c'
#    pinspath = '/coderoot/iocom/examples/buster/config/pins/grumpy/pins_io.json'
#    application_type = "controller-static"

#    sourcefiles.append('/coderoot/iocom/examples/minion/config/signals/signals.json')
#    outpath = '/coderoot/iocom/examples/minion/config/include/grumpy/signals.c'

#    sourcefiles.append('/coderoot/iocom/examples/gina/config/signals/signals.json')
#    outpath = '/coderoot/iocom/examples/tito/config/include/gina-for-tito.c'
#    pinspath = '/coderoot/iocom/examples/gina/config/pins/carol/pins_io.json'
#    application_type = "controller-static"
#    application_type = "controller-dynamic"

    is_controller = False
    is_dynamic = False
    is_slave_device = False
    if application_type == "controller-static":
        is_controller = True

    if application_type == "slave-device":
        is_controller = True
        is_slave_device = True

    if application_type == "controller-dynamic":
        is_controller = True
        is_dynamic = True

    if outpath is None:
        outpath = sourcefiles[0]

    pinlist = {}
    if pinspath is not None:
        list_pins_in_pinsfile(pinspath)

    filename, file_extension = os.path.splitext(outpath)
    cfilepath = filename + '.c'
    hfilepath = filename + '.h'

    start_c_files()

    for path in sourcefiles:
        process_source_file(path)

    if not is_controller:
        hcontent += '\n#ifndef IOBOARD_DEVICE_NAME\n'
        hcontent += '#define IOBOARD_DEVICE_NAME \"' + str(device_name) + '\"\n#endif\n'

    finish_c_files()

    write_file_only_if_changed(cfilepath, ccontent)
    write_file_only_if_changed(hfilepath, hcontent)

mymain()
